ci/feature-freeze.yml
ci/pipelines/release-manager.yml
ci/scripts/feature-freeze.sh

Pair-programmed with @thermokarst.

WIP: feature freeze branching, attempt #1

---

ci/master/bin/build.sh
ci/master/bin/env-file.sh
ci/master/bin/integration.sh
ci/master/bin/test.sh

Fixes https://github.com/qiime2/docs/issues/119

MAINT: update channel order to obtain bioconda fasttree

---

bootstrap/tasks/fly-deploy.sh
bootstrap/tasks/fly-deploy.yaml
ci/master/bin/integration.sh
ci/master/bin/tag-dev.sh
ci/master/bin/tag-release.sh
ci/master/jinja2/macros/env-file.yaml
ci/master/jinja2/macros/integration.yaml
ci/master/jinja2/macros/merge-env-files.yaml
ci/master/jinja2/macros/merge.yaml
ci/master/jinja2/macros/tag-dev.yaml
ci/master/jinja2/macros/tag-release.yaml
ci/master/jinja2/macros/unit-test.yaml

I *think* this will work. If anything stops working it's the image's fault now. So we can just update it as needed.

ENH: use worker images

---

ci/master/bin/integration.sh
ci/master/bin/test.sh
ci/master/jinja2/macros/integration.yaml
ci/master/jinja2/macros/unit-test.yaml

uses `pwd` instead of `.` now
Don't squash these commit.

Different tmpdir setup

---

ci/master/variables.yaml

Depends on https://github.com/qiime2/q2-gneiss/pull/4

ENH: add q2-gneiss

---

ci/master/variables.yaml

waiting for composition to be moved to graveyard

MAINT: remove q2-composition

---

ci/master/jinja2/macros/integration.yaml
ci/master/jinja2/macros/unit-test.yaml

This is related to the changes proposed in https://github.com/qiime2/qiime2/pull/338

MAINT: Stop setting matplotlib backend

---

ci/master/variables.yaml

BUG: release-numbers are strings

---

ci/master/variables.yaml

goes with https://github.com/qiime2/q2-metadata/pull/13

MAINT: adds q2-types dependency to q2-metadata

---

ci/master/variables.yaml

Waiting on https://github.com/qiime2/q2-diversity/pull/160.

MAINT: adds emperor dependency to q2-diversity

---

ci/master/bin/tag-dev.sh
ci/master/bin/tag-release.sh

BUG: fix tag-dev and tag-release to work with quoted releases

---

ci/master/bin/build.sh

This reverts commit 31adb8ab5e21320fd0d66ae18ca039362a73a98d.

Revert "HACK: pin conda-build to 2 (#30)"

---

ci/master/jinja2/pipelines/release-manager.yaml

Related to https://github.com/concourse/git-resource/pull/168

BUG: Update git-resource annotate path

---

ci/master/variables.yaml

https://github.com/qiime2/q2-sample-classifier/pull/117

MAINT: maturity index deps

---

ci/master/variables.yaml

MAINT: Adding in q2-fragment-insertion

---

extra/github/variables.yaml

MAINT: Wiring up new plugins to GH pipeline

---

ci/master/variables.yaml

Wires q2-diversity-lib to busywork

MAINT: adding q2-diversity-lib

---

ci/master/bin/integration.sh

Revert "HACK: Pin numpy 1.15.4"

---

ci/master/variables.yaml

This reverts commit e26cbff2323bf0100b377a8cbfdad686a4b60cfa.

Revert "Revert "HACK: remove divlib for now""

---

ci/master/variables.yaml

Change test runner to pytest for q2cli

---

ci/master/bin/unit-test.sh

This should fix the issue I think.

BUG: add evil

---

ci/master/variables.yaml

Updating variables.yaml file for 2021.8 rel

---

ci/master/bin/env-file.sh

Try to get yq out of the env we are creating. This probably won't work, but we will see.

SQUASH: @ebolyen was pretty sure this wasn't the issue, but I'm running out of ideas

---

ci/master/bin/env-file.sh

Reverts qiime2/busywork#140 As expected, didn't work

Revert "SQUASH: @ebolyen was pretty sure this wasn't the issue, but I'm running out of ideas"
